apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: partner-catalog-custom
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/alroy-tenant/partner-catalog-custom/partner-catalog-custom@sha256:e6b50215a896646c5aa1433b8986a8733058e09d398ebaca6ce513c9eb9802f4
        name: my-java-springboot
        resources: {}
status: {}
